# Generated by Django 4.2.9 on 2025-06-27 16:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=15, unique=True, verbose_name='شماره موبایل')),
                ('is_phone_verified', models.BooleanField(default=False)),
                ('referral_code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد دعوت')),
                ('national_code', models.CharField(blank=True, max_length=10, null=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد ملی')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاریخ تولد')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=100, null=True, verbose_name='استان')),
                ('name_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدرسه')),
                ('image', models.URLField(blank=True, null=True, verbose_name='عکس پروفایل')),
                ('plate_number', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره پلاک')),
                ('type_of_car', models.CharField(blank=True, choices=[('van', 'ون'), ('car', 'سواری'), ('minibus', 'مینی\u200cبوس')], max_length=10, null=True, verbose_name='نوع ماشین')),
                ('job_role', models.CharField(blank=True, choices=[('school_manager', 'مدیر مدرسه'), ('taxi_driver', 'راننده تاکسی'), ('student', 'دانش\u200cآموز')], max_length=20, null=True, verbose_name='نقش / شغل')),
                ('system_role', models.CharField(choices=[('USER', 'کاربر عادی'), ('ADMIN', 'ادمین'), ('SUPERADMIN', 'سوپر ادمین')], default='USER', max_length=20, verbose_name='نقش سیستمی')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'فعال'), ('inactive', 'غیرفعال'), ('deleted', 'حذف\u200cشده'), ('pending', 'در انتظار تأیید')], default='active', max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('referral', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
                'ordering': ['birth_date'],
            },
        ),
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('code', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('registration', 'ثبت\u200cنام'), ('login', 'ورود'), ('change_phone', 'تغییر شماره')], default='registration', max_length=20)),
                ('failed_attempts', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'کد تأیید',
                'verbose_name_plural': 'کدهای تأیید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ دعوت')),
                ('invited', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='received_referral', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cشده')),
                ('inviter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to=settings.AUTH_USER_MODEL, verbose_name='دعوت\u200cکننده')),
            ],
            options={
                'verbose_name': 'دعوت\u200cنامه',
                'verbose_name_plural': 'دعوت\u200cنامه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
