# Generated by Django 5.0 on 2025-06-28 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name_school',
            new_name='school',
        ),
    ]
