# Generated by Django 4.2.9 on 2025-06-27 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nameـschool',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='نام مدرسه'),
        ),
    ]
