# Generated by Django 4.2.9 on 2025-06-28 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_name_school_user_school'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='شماره پلاک'),
        ),
    ]
