# Generated by Django 4.2.9 on 2025-06-27 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_nameـschool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='nameـschool',
            new_name='name_school',
        ),
    ]
