# Generated by Django 5.2.1 on 2025-06-03 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_phoneotp_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='referral',
            name='reward_given',
        ),
    ]
