# Generated by Django 5.2.1 on 2025-06-03 11:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_referral_reward_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره پلاک باید به فرمت صحیح پلاک خودروهای ایران باشد، مثلا ۱۲الف۳۴۵۶', regex='^\\d{2,3}[الف-ی]\\d{3,4}$')], verbose_name='شماره پلاک'),
        ),
        migrations.AddField(
            model_name='user',
            name='vehicle_type',
            field=models.CharField(blank=True, choices=[('van', 'ون'), ('car', 'سواری'), ('minibus', 'مینی بوس')], max_length=10, null=True, verbose_name='نوع ماشین'),
        ),
    ]
