# Generated by Django 5.2.1 on 2025-06-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_plate_number_user_vehicle_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('school_manager', 'مدیر مدرسه'), ('taxi_driver', 'راننده تاکسی'), ('student', 'دانش\u200cآموز')], max_length=20, null=True, verbose_name='نقش / شغل'),
        ),
    ]
