# Generated by Django 5.2.1 on 2025-06-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='vehicle_type',
        ),
        migrations.AddField(
            model_name='user',
            name='type_of_car',
            field=models.CharField(blank=True, choices=[('van', 'ون'), ('car', 'سواری سبک'), ('minibus', 'مینی بوس')], max_length=10, null=True, verbose_name='نوع ماشین'),
        ),
    ]
