# Generated by Django 5.2.1 on 2025-06-04 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_user_vehicle_type_user_type_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type_of_car',
            field=models.CharField(blank=True, choices=[('van', 'ون'), ('car', 'سواری سب'), ('minibus', 'مینی بوس')], max_length=10, null=True, verbose_name='نوع ماشین'),
        ),
    ]
