# Generated by Django 5.2.1 on 2025-06-04 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_type_of_car'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره پلاک باید به فرمت صحیح پلاک خودروهای ایران باشد، مثلا ۱۲الف۳۴۵۶', regex='^\\d{2,3}[الف-ی]\\d{3,4}$')], verbose_name='شماره پلاک'),
        ),
    ]
