# Generated by Django 5.2.1 on 2025-06-04 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_user_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='شماره پلاک باید به فرمت صحیح پلاک خودروهای ایران باشد، مثلا ۲۲۲ی۲۲ ۲۲', regex='^\\d{2}\\d{3}\\s?[الف-ی]\\d{2}$')], verbose_name='شماره پلاک'),
        ),
    ]
