# Generated by Django 5.2.1 on 2025-06-04 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_user_plate_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='plate_number',
            field=models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='شماره پلاک'),
        ),
    ]
