# Generated by Django 5.2.1 on 2025-06-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_user_plate_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='failed_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='phoneotp',
            name='purpose',
            field=models.CharField(choices=[('registration', 'ثبت\u200cنام'), ('login', 'ورود'), ('change_phone', 'تغییر شماره')], default='registration', max_length=20),
        ),
    ]
