# Generated by Django 5.2.1 on 2025-06-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_phoneotp_failed_attempts_alter_phoneotp_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phoneotp',
            name='code',
            field=models.CharField(max_length=128),
        ),
    ]
